#pragma once

#define FEBASICAPPLICATION_VERSION_MAJOR 0
#define FEBASICAPPLICATION_VERSION_MINOR 4
#define FEBASICAPPLICATION_VERSION_PATCH 4

#define FEBASICAPPLICATION_BUILD_NUMBER 75
#define FEBASICAPPLICATION_BUILD_BRANCH_OFFSET 0
#define FEBASICAPPLICATION_GIT_HASH "57a4102"
#define FEBASICAPPLICATION_GIT_BRANCH "master"
#define FEBASICAPPLICATION_BUILD_TIMESTAMP "20260209223138"
#define FEBASICAPPLICATION_GIT_DIRTY 1
